tmeshkova/qtmozembed

src/quickmozview.cpp, src/quickmozview.h
As we are currently dropping glcontext when the application
using quickmozview becomes invisible (covered by another application), this timer
does not serve any purpose anymore.
=> [qtmozembed] Remove timer from background

src/qgraphicsmozview_p.cpp, src/qgraphicsmozview_p.h, src/quickmozview.cpp
x and y coordinates that are passed to firstPaint signal are always
negative when resetting painted state.
=> [qtmozembed] Reset painted state immediately on back/forward/reload/load

src/quickmozview.cpp, src/quickmozview.h
Previously there was a chance that QGraphicsMozViewPrivate::UpdateViewSize
did not update EmbedLiteView::SetGLViewPortSize because mHasContext was still
false. This in turn led to a crash when EmbedLiteCompositorParent::RenderGL()
tried to publish a frame that was an empty.
This commit adds a updateViewSize signal that is connected to the
QGraphicsMozViewPrivate::UpdateViewSize (normal queued connection). By doing
this QuickMozView::createThreadRenderObject can update mHasContext
and EmbedLiteView::SetGLViewPortSize.
See also: https://github.com/tmeshkova/gecko-dev/pull/45
=> [qtmozembed] Update view size always when context info is updated

src/quickmozview.cpp
Uninitialized pointer seems to be the reason for github.com/tmeshkova/qtmozembed/issues/93
JB#23892
=> [rendering] Initialize texture pointer to null

src/quickmozview.cpp
Don't see reason why we'd have this one. In addition, this has an impact
on rendering performance.
=> [qtmozembed] Remove clearBeforeRendering false

src/qgraphicsmozview.cpp, src/qgraphicsmozview.h, src/qmozview_defined_wrapper.h, src/quickmozview.cpp
Instead of implementing scrollTo() method, application should scroll by sending 'embedui:scrollTo' message
=> [qtmozembed] Remove scrollTo() method from QGraphicsMozView and QuickMozView classes

src/qgraphicsmozview_p.cpp, src/qgraphicsmozview_p.h, src/quickmozview.cpp
This makes possible to call these methods before view is created. When
the view initialized callback is called, pending initialization steps
are executed.
=> [qtmozembed] Move load, loadFrameScript, addMessageListener(s) to the private class

src/qgraphicsmozview.cpp, src/qgraphicsmozview_p.cpp, src/qgraphicsmozview_p.h, src/quickmozview.cpp, src/quickmozview.h
Move inputMethodQuery, inputMethodEvent, keyPressEvent, and
keyReleaseEvent to the private class.
This is preparation for opengl based public interface / generic cleanup.
=> [qtmozembed] Move text input handling to the private class

src/qgraphicsmozview.cpp, src/qgraphicsmozview_p.cpp, src/qgraphicsmozview_p.h, src/qmozview_defined_wrapper.h, src/qmozview_templated_wrapper.h, src/qopenglwebpage.cpp, src/qopenglwebpage.h, src/quickmozview.cpp, src/src.pro
Work-in-progress do not merge until required dependencies are merged!
MOZ_USE_EXTERNAL_WINDOW environment variable needs to be set.
This also requires that EmbedLitePuppetWidget requests gl context and
MOZ_LAYERS_PREFER_OFFSCREEN is not set by EmbedLiteAppThreadParent.
Meaning that following embedlite pull requests are needed:
https://github.com/tmeshkova/gecko-dev/pull/48
https://github.com/nemomobile-packages/gecko-dev/pull/4
https://github.com/nemomobile-packages/gecko-dev/pull/5 (same as https://github.com/tmeshkova/gecko-dev/pull/48 but against gecko 31)
https://github.com/tmeshkova/qtmozembed/pull/112
https://github.com/tmeshkova/qtmozembed/pull/113
https://github.com/tmeshkova/qtmozembed/pull/114
https://github.com/tmeshkova/qtmozembed/pull/115 …
=> [qtmozembed] Add a web page supporing OMTC and external window/surface

src/qgraphicsmozview.cpp, src/qgraphicsmozview_p.cpp, src/qopenglwebpage.cpp, src/quickmozview.cpp
Without this fix following kind of error messages are printed when
LoadFrameScript, ResumeView, or SuspendView is called before view is initialized:
IPDL protocol error: Handler for LoadFrameScript returned error code
deserialized, but the handler returned false (indicating failure)
=> [qtmozembed] Don't pass calls through before view is initialized.

src/qopenglwebpage.cpp, src/qopenglwebpage.h
Previously QQuickItem handled key/input event dispatch to
event methods.
=> [qtmozembed] Dispatch input events in QOpenGLWebPage

src/qgraphicsmozview.cpp, src/qgraphicsmozview_p.cpp, src/qgraphicsmozview_p.h, src/qmozview_defined_wrapper.h, src/qmozview_templated_wrapper.h, src/qopenglwebpage.cpp, src/quickmozview.cpp
JB#28056
Add draw underlay implementation for the opengl web page. Background color of the web page is used as glClearColor.
See also:
https://github.com/nemomobile-packages/gecko-dev/pull/8
https://github.com/tmeshkova/gecko-dev/pull/50
=> [qtmozembed] Add draw underlay implementation.

src/qgraphicsmozview_p.cpp, src/qgraphicsmozview_p.h, src/qopenglwebpage.cpp, src/qopenglwebpage.h
Rebased and updated.
See also PR:
https://github.com/nemomobile-packages/gecko-dev/pull/9
https://github.com/nemomobile-packages/gecko-dev/pull/10
https://github.com/tmeshkova/gecko-dev/pull/52
This PR contains also a small fix that kills running move monitor when monitor restarted.
=> Use screenrotation api for opengl webpage

src/qgraphicsmozview.cpp, src/qgraphicsmozview_p.cpp, src/qgraphicsmozview_p.h, src/qmozgrabresult.cpp, src/qmozgrabresult.h, src/qmozview_defined_wrapper.h, src/qmozview_templated_wrapper.h, src/qopenglwebpage.cpp, src/qopenglwebpage.h, src/quickmozview.cpp, src/src.pro
Contains two commits.
First one adds drawOverlay and the 2nd commit adds QQuickItem::grabToImage like API for openglwebpage.
Requires:
https://github.com/nemomobile-packages/gecko-dev/pull/11 (nemo embedlite 31)
https://github.com/tmeshkova/gecko-dev/pull/54 (embedlite esr)
https://github.com/tmeshkova/gecko-dev/pull/56 (embedlite)
=> Implementation DrawWindowOverlay 

src/qgraphicsmozview_p.h
Currently 3 public view implementations (QuickMozView, QGraphicsView,
QOpenGLWebPage) use the same common private part,
QGraphicsMozViewPrivate. In all 3 cases the public view implementations
create an instance of QGrapicsMozViewPrivate in their constructors and
remove it in desctructor. At the same time a pointer to the public view
implementaton is storred in QGraphicsMozViewPrivate::q variable.
Unfortunately the QScopedPointer template class is used to manage the
pointer. As a result when public view is destroyed it calls delete on
it's private part, which in turn removes public view once again when
QScopedPointer goes out of scope. The public view implementation is
destroyed twice.
This patch replaces QScopedPointer with QPointer which should ensure
each public view type is only …
=> Remove cyclic dependency between public and private part of MozView

src/qmozgrabresult.cpp, src/qmozgrabresult.h, src/qopenglwebpage.cpp, src/qopenglwebpage.h
The QMozGrabResult object is expected to be created from the main
application thread. Unfotunately the QMozGrabResult::captureImage is
currently directly connected to QOpenGLWebPage::afterRendering slot
which is invoked on Gecko's compositor thread. This means the object can
actually be in use when the UI thread removes it.
To fix the problem QOpenGLWebPage was extended to keep a list of weak
refs to QMozGrabResuls it was asked to handle. When
QOpenGLWebpage::drawOverlay is invoked, the code iterates over pending
grab results, tries to convert weak refs into strong ones and only
invokes the captureImage function when the conversion is successful.
If the UI thread removed the object before the capture process was
realized on the compostor thread the weak ref will be invalid and the
image …
=> Fix use after free crash in thumbnail capturing code JB#28888

src/qopenglwebpage.cpp, src/qopenglwebpage.h
1. Remove setIsActive signal. It was probably copied from QQuickMozView.
Nothing emits it in case of QOpenGLPage so the codepath is dead.
2. Merge setActive and SetIsActive functions. They are pretty simple and
SetIsActive is only called from setActive anyway. It's easier to
understand the code without two activation calls.
3. Set QOpenGLPage::mActive default value to false. The code actually
implies the view remains inactive until it's initialized.
QOpenGLWebPage::processViewInitialization always calls
forceActiveFocus which forces active state. This also means we can
simply ignore setActive calls until view is initialized.
=> [qtmozembed] Simplify QOpenGLPage::active property handling. JB#28807

src/qopenglwebpage.cpp, src/qopenglwebpage.h
With multi window browser backgrounding is handled in the
browser content window.
JB#28880
=> [qtmozembed] Remove unused background property.

src/qopenglwebpage.cpp
Instead of assert return if view not initialized. The processViewInitialization
takes care of initial focus. SetIsFocused needs to go through
private class so that mViewIsFocused gets updated.
=> [qtmozembed] Fix forceActiveFocus of openglwebpage

src/qopenglwebpage.cpp, src/qopenglwebpage.h
The embedlite view is created when initialize() is called. This
needs to be called as a last step when instantiating a page.
When the page is wrapped inside a qml component we cannot
pass additional argument to the QQmlComponent::beginCreate.
Once state information is set for the instance, before calling
QQmlComponent::completeCreate complete initialization by
calling initialize().
=> [qtmozembed] Add initialize method to complete instantiation. Contributes JB#27557

src/qopenglwebpage.cpp, src/qopenglwebpage.h
Currently when the screen is rotated we end up sneding size updates to
the engine 3 times. Only the last size update is actuall correct.
For example on Jolla phone with screen size of 540x960 when the screen
is rotated from potrtrait mode to landscape.
1. QOpenGLWebPage::updateContentOrientation is called which in turn
calls QOpenGLWebPage::setSurfaceSize(960x540, Landscape). Since the
setSurfaceSize does not modify d->mSize, but it does call
d->UpdateViewSize() will end up notifying gecko about view size
change to 540x960 (old size still storred in d->mSize).
2. QML layer calls QOpenGLWebPage::setHeight(540), which in turn calls
::setSize(540x540). This invalid size is sent to the engine.
3. QML layer calls QOpenGLWebPage::setWidth(960), which calls
::setSize(960x540). This is the …
=> [qtmozembed] Don't spam gecko with unnecessary size updates. JB#29317

src/qopenglwebpage.cpp
If the currently active QOpenGLWebPage is being destroyed clear it's
compositing surface (shared with all other QOpenGLWebPage instances).
This should ensure we won't see the content of just closed page before
another page draws it's content. An extreme case of such problem can be
seen when the page being closed is the only one being open. In such
case the compositing surface will contain the content of the just
closed page until the user loads a new one.
=> Clear compositing surface on active page destruction. JB#29995

src/qmozcontext.cpp, src/qmozcontext.h
This just exposes EmbedLiteApp::{PostTask|PostCompositorTask|CancelTask}
functions in QMozContext.
=> [qtmozembed] Expose EmbedLiteApp's task posting functionality. Contributes to JB#30162.

src/qopenglwebpage.cpp
With the newly introduced EmbedLite compositor task posting fuctionality
the necessary surface clearing can be done easily by the application
itself. There is no need for the QOpenGLWebPage to take care of this
detail.
This reverts commit a74040242f4c4629a35756810a848ad2e2b70ce1.
=> Revert "Clear compositing surface on active page destruction. JB#29995"

src/qmozview_defined_wrapper.h
In some unit tests we need to build custom environment
through using mock objects. In order to resolve methods
correctly those ones that need to be overriden should be
marked as virtual.
=> Mark methods virtual to be able to override them in mock objects

src/qgraphicsmozview_p.cpp
Also emit touchend event before touchmove when handling Qt's touchEvent.
This makes the test suite http://w3c-test.org/touch-events/ pass all
cases and improves pinching at m.here.com.
=> [multitouch] Produce separate events for every pressed or removed touch point
